"""Add Trade table

Revision ID: 4af881e59867
Revises: 963886fb8d9c
Create Date: 2024-05-23 07:08:18.021785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4af881e59867'
down_revision = '963886fb8d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('s_l', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('t_p', sa.Float(), nullable=False))
        batch_op.drop_column('sl')
        batch_op.drop_column('tp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tp', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('sl', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('t_p')
        batch_op.drop_column('s_l')

    # ### end Alembic commands ###
