"""Add Trade table

Revision ID: 534ed6705f0d
Revises: 4af881e59867
Create Date: 2024-05-23 10:12:00.919702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '534ed6705f0d'
down_revision = '4af881e59867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comm', sa.Float(), nullable=False))
        batch_op.drop_column('commission')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commission', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('comm')

    # ### end Alembic commands ###
