"""update

Revision ID: 625bb8c55a6c
Revises: 9fd47ae43f02
Create Date: 2024-05-25 07:11:54.659627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '625bb8c55a6c'
down_revision = '9fd47ae43f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pips', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Interval(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_column('duration')
        batch_op.drop_column('pips')

    # ### end Alembic commands ###
