"""Update Trade model to use DECIMAL for financial fields

Revision ID: 6e0753c6eec2
Revises: bee5fee69b8f
Create Date: 2024-05-25 14:28:49.277749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e0753c6eec2'
down_revision = 'bee5fee69b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('s_l',
               existing_type=mysql.FLOAT(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('t_p',
               existing_type=mysql.FLOAT(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('close_price',
               existing_type=mysql.FLOAT(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('comm',
               existing_type=mysql.FLOAT(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('taxes',
               existing_type=mysql.FLOAT(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('swap',
               existing_type=mysql.FLOAT(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('profit',
               existing_type=mysql.FLOAT(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.alter_column('profit',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('swap',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('taxes',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('comm',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('close_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('t_p',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('s_l',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
