"""Add Trade table

Revision ID: 963886fb8d9c
Revises: bcf56bb8885e
Create Date: 2024-05-22 20:32:38.647489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '963886fb8d9c'
down_revision = 'bcf56bb8885e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trade_type', sa.String(length=10), nullable=False))
        batch_op.alter_column('item',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('sl',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('tp',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('close_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('close_price',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('commission',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('taxes',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('swap',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('profit',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=10), nullable=False))
        batch_op.alter_column('profit',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('swap',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('taxes',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('commission',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('close_price',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('close_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('tp',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('sl',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('item',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('trade_type')

    # ### end Alembic commands ###
