"""Add broker_name, platform, equity, and balance to UserData

Revision ID: a6b6c0ce5aec
Revises: 625bb8c55a6c
Create Date: 2024-05-25 09:57:26.677190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b6c0ce5aec'
down_revision = '625bb8c55a6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('broker_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('platform', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('equity', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.drop_column('balance')
        batch_op.drop_column('equity')
        batch_op.drop_column('platform')
        batch_op.drop_column('broker_name')

    # ### end Alembic commands ###
