"""Add UserData table

Revision ID: afbde97f53c7
Revises: 38978077245f
Create Date: 2024-05-22 10:52:22.330897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'afbde97f53c7'
down_revision = '38978077245f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_trading_days', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('max_daily_loss', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('max_loss', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('profit_target', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('instrument', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('trading_session', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('risk_reward', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('daily_max_loss', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('consecutive_losers', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('trading_strategy', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('timeframes', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('trades_per_day', sa.String(length=255), nullable=True))
        batch_op.drop_column('rules')
        batch_op.drop_column('objective')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objective', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('rules', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('trades_per_day')
        batch_op.drop_column('timeframes')
        batch_op.drop_column('trading_strategy')
        batch_op.drop_column('consecutive_losers')
        batch_op.drop_column('daily_max_loss')
        batch_op.drop_column('risk_reward')
        batch_op.drop_column('trading_session')
        batch_op.drop_column('instrument')
        batch_op.drop_column('profit_target')
        batch_op.drop_column('max_loss')
        batch_op.drop_column('max_daily_loss')
        batch_op.drop_column('min_trading_days')

    # ### end Alembic commands ###
