"""Add checklist category and item tables

Revision ID: b38ebc5e2523
Revises: dd4dd96856e7
Create Date: 2024-06-02 14:38:52.551078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b38ebc5e2523'
down_revision = 'dd4dd96856e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))
        batch_op.drop_column('checked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
