"""Add fields for screenshots, comment, and strategy to Trade model

Revision ID: b7e10c749eb2
Revises: 6e0753c6eec2
Create Date: 2024-05-26 12:46:14.710826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e10c749eb2'
down_revision = '6e0753c6eec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('strategy', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('screenshot1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('screenshot2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('screenshot3', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_column('screenshot3')
        batch_op.drop_column('screenshot2')
        batch_op.drop_column('screenshot1')
        batch_op.drop_column('strategy')
        batch_op.drop_column('comments')

    # ### end Alembic commands ###
